repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.284
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
        exclude: .gitlab-ci.yml
      - id: check-toml
      - id: end-of-file-fixer

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pytest-style
        args:
          - --select=PT
          - --pytest-parametrize-names-type=csv

exclude: "docs/.*"
