[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = [
    "E", # pycodestyle error
    "F", # Pyflakes
    "I", # isort
    "PLE", # Pylint error
    "PLW", # Pylint warning
    "G", # flake8-logging-format
    "N", # pep8-naming
    "A", # flake8-builtins
]

ignore = [
    "A003", # builtin-attribute-shadowing
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = [
    "F841", # unused-variable
    "F541", # f-string-missing-placeholders
]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    ".proto",
    "monitor/reader/proto/device_pb2.py",
]

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.8
target-version = "py38"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.black]
line-length = 120
target-version = ['py38']

[tool.isort]
py_version = 38
profile = "black"
