# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x06\x64\x65vice\"7\n\nMemoryInfo\x12\r\n\x05total\x18\x01 \x01(\x03\x12\x0c\n\x04\x66ree\x18\x02 \x01(\x03\x12\x0c\n\x04used\x18\x03 \x01(\x03\"F\n\x0bTemperature\x12\x11\n\x07\x43\x65lsius\x18\x01 \x01(\x02H\x00\x12\x14\n\nFahrenheit\x18\x02 \x01(\x02H\x00\x42\x0e\n\x0ctemp_reading\"C\n\x07Process\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06memory\x18\x03 \x01(\x03\x12\r\n\x05usage\x18\x04 \x01(\x02\"k\n\tBasicInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0e\n\x06serial\x18\x03 \x01(\t\x12\x0c\n\x04uuid\x18\x04 \x01(\t\x12\x14\n\x0c\x61rchitecture\x18\x05 \x01(\t\x12\r\n\x05\x62rand\x18\x06 \x01(\t\"\xa6\x01\n\nMatrixInfo\x12(\n\x0btemperature\x18\x01 \x01(\x0b\x32\x13.device.Temperature\x12\'\n\x0bmemory_info\x18\x02 \x01(\x0b\x32\x12.device.MemoryInfo\x12\r\n\x05usage\x18\x03 \x01(\x02\x12\x14\n\x0cmemory_usage\x18\x04 \x01(\x02\x12 \n\x07process\x18\x05 \x03(\x0b\x32\x0f.device.Process\"\x91\x01\n\x05NVGPU\x12\x1f\n\x04info\x18\x01 \x01(\x0b\x32\x11.device.BasicInfo\x12\"\n\x06matrix\x18\x02 \x01(\x0b\x32\x12.device.MatrixInfo\x12\x14\n\x0c\x63uda_version\x18\x03 \x01(\x05\x12\x15\n\rcuda_capacity\x18\x04 \x01(\t\x12\x16\n\x0e\x64river_version\x18\x05 \x01(\t\"+\n\nNVGPUArray\x12\x1d\n\x06nvg_pu\x18\x01 \x03(\x0b\x32\r.device.NVGPU\"J\n\x03\x43PU\x12\x1f\n\x04info\x18\x01 \x01(\x0b\x32\x11.device.BasicInfo\x12\"\n\x06matrix\x18\x02 \x01(\x0b\x32\x12.device.MatrixInfob\x06proto3')



_MEMORYINFO = DESCRIPTOR.message_types_by_name['MemoryInfo']
_TEMPERATURE = DESCRIPTOR.message_types_by_name['Temperature']
_PROCESS = DESCRIPTOR.message_types_by_name['Process']
_BASICINFO = DESCRIPTOR.message_types_by_name['BasicInfo']
_MATRIXINFO = DESCRIPTOR.message_types_by_name['MatrixInfo']
_NVGPU = DESCRIPTOR.message_types_by_name['NVGPU']
_NVGPUARRAY = DESCRIPTOR.message_types_by_name['NVGPUArray']
_CPU = DESCRIPTOR.message_types_by_name['CPU']
MemoryInfo = _reflection.GeneratedProtocolMessageType('MemoryInfo', (_message.Message,), {
  'DESCRIPTOR' : _MEMORYINFO,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.MemoryInfo)
  })
_sym_db.RegisterMessage(MemoryInfo)

Temperature = _reflection.GeneratedProtocolMessageType('Temperature', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURE,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.Temperature)
  })
_sym_db.RegisterMessage(Temperature)

Process = _reflection.GeneratedProtocolMessageType('Process', (_message.Message,), {
  'DESCRIPTOR' : _PROCESS,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.Process)
  })
_sym_db.RegisterMessage(Process)

BasicInfo = _reflection.GeneratedProtocolMessageType('BasicInfo', (_message.Message,), {
  'DESCRIPTOR' : _BASICINFO,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.BasicInfo)
  })
_sym_db.RegisterMessage(BasicInfo)

MatrixInfo = _reflection.GeneratedProtocolMessageType('MatrixInfo', (_message.Message,), {
  'DESCRIPTOR' : _MATRIXINFO,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.MatrixInfo)
  })
_sym_db.RegisterMessage(MatrixInfo)

NVGPU = _reflection.GeneratedProtocolMessageType('NVGPU', (_message.Message,), {
  'DESCRIPTOR' : _NVGPU,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.NVGPU)
  })
_sym_db.RegisterMessage(NVGPU)

NVGPUArray = _reflection.GeneratedProtocolMessageType('NVGPUArray', (_message.Message,), {
  'DESCRIPTOR' : _NVGPUARRAY,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.NVGPUArray)
  })
_sym_db.RegisterMessage(NVGPUArray)

CPU = _reflection.GeneratedProtocolMessageType('CPU', (_message.Message,), {
  'DESCRIPTOR' : _CPU,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:device.CPU)
  })
_sym_db.RegisterMessage(CPU)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEMORYINFO._serialized_start=24
  _MEMORYINFO._serialized_end=79
  _TEMPERATURE._serialized_start=81
  _TEMPERATURE._serialized_end=151
  _PROCESS._serialized_start=153
  _PROCESS._serialized_end=220
  _BASICINFO._serialized_start=222
  _BASICINFO._serialized_end=329
  _MATRIXINFO._serialized_start=332
  _MATRIXINFO._serialized_end=498
  _NVGPU._serialized_start=501
  _NVGPU._serialized_end=646
  _NVGPUARRAY._serialized_start=648
  _NVGPUARRAY._serialized_end=691
  _CPU._serialized_start=693
  _CPU._serialized_end=767
# @@protoc_insertion_point(module_scope)
